version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3310:3306"
    volumes:
      - ./db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: django
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8183:80
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: django
        MYSQL_USER: django
        MYSQL_PASSWORD: django
        PMA_HOST: db
    depends_on:
        - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true
    volumes:
      - .:/code
      - ~/tmp2/Download/ip/:/images
    ports:
      - "8000:8000"
    depends_on:
      - db

